modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/Pipsqueak737/Opulence/issues"
license = "GPLv3"

[[mods]]
modId = "opulence"
version = "${version}"
displayName = "Opulence"
authors = "Pipsqueak737"
description = '''
Adds new decorative variants of expensive blocks like gold, diamond, and emerald!
'''
logoFile = "logo.png"

[[dependencies.opulence]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.opulence]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.opulence]]
modId = "pollen"
mandatory = true
versionRange = "[1.5.0,)"
ordering = "AFTER"
side = "BOTH"

[modproperties.opulence]
catalogueItemIcon = "opulence:engraved_emerald"